### ISSUE TITLE
error

### ISSUE THREAD

**Issue by granula** [mobb111/ruby-brainwalet-destroyer#1]
Enter file name: words.txt
Enter number of passphrases: cain.txt
Enter number for repeat word x, press 1 no repeat : 1
Enter salt for sha256: dictionary.txt
Enter number for API:

Bitcoinlegacy   (1):
Blockchain      (2):
Blockexplorer   (3):
Insight Bitpay  (4):
Blockonomics    (5):
Blockchyper     (6):
Chain.so        (7):
BTC.com         (8):
Bitstamp        (9):

Select API: 1

  |--------- Wallet Address ---------||-------------------- Private Key -------------
Traceback (most recent call last):
  File "ruby.py", line 421, in <module>
    Ruby()
  File "ruby.py", line 389, in Ruby
    data[0] = privateKey()
  File "ruby.py", line 76, in privateKey
    for item in range(int(n))]*(int(f))
ValueError: invalid literal for int() with base 10: 'cain.txt'

**Comment by granula** [comment]
Why only one api? You can do everything in turn.
If to one there is no connection, at once tries another, automatically

**Comment by granula** [comment]
Enter number for repeat word x, press 1 no repeat : ?????

**Comment by mobb111** [comment]
:) enter file name is correct, enter number of passphrasses incorrect u need number ther 1-26 what ever u want number, enter salt for sha is password to more secure btc so if u combine them with 123456 maybe u unlock somebody privatekey with balance,  in repeat zone u select passphrase 1 repeat x3 some people use that so i did thid becose u can find balance, api u select from 1 to 9

**Comment by mobb111** [comment]
try combine them u will see this program is great if u find balance dont forget donate :)

**Comment by mobb111** [comment]
and if u got any idea tell me and we gona improve hack

**Comment by mobb111** [comment]
this hack is hardcore

**Comment by granula** [comment]
the program runs very slowly (((

**Comment by mobb111** [comment]
hm what cpu u got

**Comment by mobb111** [comment]
and internet connection? if connection is weak it will work slow

**Comment by granula** [comment]
https://pix.my/QNjKig
100mb/s

**Comment by mobb111** [comment]
email?

**Comment by granula** [comment]
ok.email

**Comment by mobb111** [comment]
ano.mobb@gmail.com

**Comment by granula** [comment]
https://pix.my/zXS3jR
If to one there is no connection, at once tries another, automatically

**Comment by mobb111** [comment]
will work on that

**Comment by granula** [comment]
Look further in this direction https://github.com/anthiras/ProverbGenerator
