### ISSUE TITLE
iancoleman.io/bip39/

### ISSUE THREAD

**Issue by granula** [mobb111/ruby-brainwalet-destroyer#5]
Please make Bip39 Derivation Path Bip44

**Comment by mobb111** [comment]
working on that be here in few days ;)

**Comment by granula** [comment]
> 
> 
> working on that be here in few days ;)

Just as you promised to add brainflayer ???

https://pix.my/sW3ID8

**Comment by granula** [comment]
> 
> 
> working on that be here in few days ;)

You do not keep your word. You have deceived us.

**Comment by mobb111** [comment]
hi why i decive u? i got life, so be patient, i change system and trying other stuff but if u think that that ok, just dont folow me

**Comment by mobb111** [comment]
im trying barinflayer to on kali so i keep my word

**Comment by mobb111** [comment]
but need time
